version: "3.8"

services:
  db:
    image: postgres:14
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bktest
      - POSTGRES_PASSWORD=hello
    networks:
      - assessment
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  testdb:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bktest
      - POSTGRES_PASSWORD=hello
    networks:
      - assessment
    volumes:
      - testdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    image: registry.sabbir.dev/bk-rest-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=bktest
      - DB_PASSWORD=hello
      - DB_NAME=postgres
      - SSL_MODE=disable
      - JWT_SECRET=bk-go-dev
    ports:
      - 8888:8888
    depends_on:
      db:
        condition: service_healthy
    networks:
      - assessment

volumes:
  dbdata:
  testdata:

networks:
  assessment: