- hosts: cp
  become: no

  tasks:
  - name: rolling upate
    ansible.builtin.shell:
      cmd: kubectl rollout restart deploy bk-app

  - name: changing cause
    ansible.builtin.shell:
      cmd: kubectl annotate deployments bk-app kubernetes.io/change-cause="{{commitId}}"
